server:
  servlet:
    context-path: /boy
  post: 8080

spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.18.66:1521:orcl
    username: dopdba
    password: dopdba
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

girl:
  name: zhangliqing
  age: 20
  cupsize: d